version: '3.7'

services:
  # database:
  #   image: postgres:10.5
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=admin_bot_db
  #   logging:
  #     options:
  #       max-size: 10m
  #       max-file: "3"
  #   ports:
  #     - '5438:5432'
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - dbnet

  admin_bot:
    image: ghcr.io/kenwoodfox/snub:feat-initalversion
    # networks:
    #   - dbnet
    # depends_on:
    #   - database
    ports:
      - '8080:8080'
    restart: "always"

# networks:
#   dbnet:
#     driver: bridge
